# Generated by Django 5.2.1 on 2025-06-13 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('adhaar_no', models.BigIntegerField(blank=True, null=True)),
                ('pan_no', models.BigIntegerField(blank=True, null=True)),
                ('qualification', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherYearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.yearlevel')),
            ],
            options={
                'unique_together': {('teacher', 'year_level')},
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='year_levels',
            field=models.ManyToManyField(through='teacher.TeacherYearLevel', to='director.yearlevel'),
        ),
    ]
