# Generated by Django 5.1.6 on 2025-05-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='adhaar_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pan_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
