# Generated by Django 5.1.6 on 2025-05-08 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_admission'),
        ('teacher', '0002_alter_teacher_adhaar_no_alter_teacher_pan_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherYearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.yearlevel')),
            ],
            options={
                'unique_together': {('teacher', 'year_level')},
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='year_levels',
            field=models.ManyToManyField(through='teacher.TeacherYearLevel', to='director.yearlevel'),
        ),
    ]
