[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip",
  "python310Packages.setuptools",
  "python310Packages.wheel"
]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]



