[phases.setup]
nixPkgs = ["python310Full"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "python3 -m pip install -r requirements.txt"]

[start]
cmd = "python manage.py runserver 0.0.0.0:8000"



