# Generated by Django 5.1.1 on 2024-09-13 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admission_date', models.DateField()),
                ('previous_school_name', models.CharField(max_length=200)),
                ('previous_standard_studied', models.CharField(max_length=200)),
                ('tc_letter', models.CharField(max_length=200)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.guardian')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.yearlevel')),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
                'db_table': 'Admission',
            },
        ),
    ]
