# Generated by Django 5.1.6 on 2025-06-15 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0001_initial'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.guardian'),
        ),
        migrations.AddField(
            model_name='admission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student'),
        ),
        migrations.AddField(
            model_name='bankingdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.city'),
        ),
        migrations.AddField(
            model_name='classperiod',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='classperiod',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.classroom'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.classroomtype'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.country'),
        ),
        migrations.AddField(
            model_name='director',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.guardian'),
        ),
        migrations.AddField(
            model_name='document',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
        migrations.AddField(
            model_name='document',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_types',
            field=models.ManyToManyField(to='director.documenttype'),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='file',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='director.document'),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='admissions',
            field=models.ManyToManyField(blank=True, related_name='handled_by_staff', to='director.admission'),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='director.department'),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='managed_by_staff', to='student.student'),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='managed_by_staff', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='officestaff',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='office_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='director.officestaff'),
        ),
        migrations.AddField(
            model_name='classperiod',
            name='end_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='end_time', to='director.period'),
        ),
        migrations.AddField(
            model_name='classperiod',
            name='start_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='start_time', to='director.period'),
        ),
        migrations.AddField(
            model_name='period',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.schoolyear'),
        ),
        migrations.AddField(
            model_name='admission',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.schoolyear'),
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.state'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.state'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.department'),
        ),
        migrations.AddField(
            model_name='classperiod',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.subject'),
        ),
        migrations.AddField(
            model_name='term',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.schoolyear'),
        ),
        migrations.AddField(
            model_name='classperiod',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.term'),
        ),
        migrations.AddField(
            model_name='admission',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.yearlevel'),
        ),
        migrations.AddField(
            model_name='yearlevelfee',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.feetype'),
        ),
        migrations.AddField(
            model_name='yearlevelfee',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.yearlevel'),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='year_level_fees',
            field=models.ManyToManyField(to='director.yearlevelfee'),
        ),
    ]
