# Generated by Django 5.1.6 on 2025-05-13 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_admission'),
        ('student', '0003_alter_student_enrolment_date'),
        ('teacher', '0003_teacheryearlevel_teacher_year_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('admissions', models.ManyToManyField(blank=True, related_name='handled_by_staff', to='director.admission')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='director.department')),
                ('student', models.ManyToManyField(blank=True, related_name='managed_by_staff', to='student.student')),
                ('teacher', models.ManyToManyField(blank=True, related_name='managed_by_staff', to='teacher.teacher')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Office Staff',
                'verbose_name_plural': 'Office Staff',
                'db_table': 'OfficeStaff',
            },
        ),
    ]
