# Generated by Django 5.0.3 on 2025-05-08 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_admission'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash')], max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('banking_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='director.bankingdetail')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='student.student')),
            ],
            options={
                'verbose_name': 'Fee',
                'verbose_name_plural': 'Fee',
                'db_table': 'Fee',
            },
        ),
    ]
