# Generated by Django 5.0.3 on 2025-05-08 06:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0003_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
