# Generated by Django 5.0.2 on 2024-05-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0003_alter_director_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelTable(
            name='address',
            table='Address',
        ),
    ]
