# Generated by Django 5.0.3 on 2025-05-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0004_admission_total_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='total_fee',
        ),
    ]
