# Generated by Django 5.0.3 on 2025-05-08 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0005_remove_admission_total_fee'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='amount',
            new_name='total_fee',
        ),
        migrations.AddField(
            model_name='fee',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='director.term'),
        ),
        migrations.AddField(
            model_name='fee',
            name='year_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='director.yearlevel'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='banking_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='director.bankingdetail'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='payment_mode',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
