# Generated by Django 5.0.3 on 2025-05-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0006_rename_amount_fee_total_fee_fee_receipt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='receipt_number',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
