# Generated by Django 5.0.3 on 2025-05-08 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0007_alter_fee_receipt_number'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='total_fee',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='term',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='year_level',
        ),
        migrations.AlterField(
            model_name='fee',
            name='banking_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='director.bankingdetail'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='payment_mode',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='student.student'),
        ),
    ]
