# Generated by Django 5.0.3 on 2025-05-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0009_rename_amount_fee_total_fee_fee_receipt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='receipt_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
