# Generated by Django 5.0.3 on 2025-05-09 06:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0010_alter_fee_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='receipt_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
