# Generated by Django 5.0.3 on 2025-05-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0011_alter_fee_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
