# Generated by Django 5.0.3 on 2025-05-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0012_fee_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'FeeType',
                'verbose_name_plural': 'FeeType',
                'db_table': 'FeeType',
            },
        ),
        migrations.RemoveField(
            model_name='fee',
            name='banking_detail',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='total_fee',
        ),
    ]
