# Generated by Django 5.0.3 on 2025-05-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0013_feetype_remove_fee_banking_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='student',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='term',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='year_level',
        ),
        migrations.DeleteModel(
            name='FeeType',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
