# Generated by Django 5.0.3 on 2025-05-12 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0015_feestructure_feetype_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='term',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='year_level',
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='director.feestructure'),
        ),
    ]
