# Generated by Django 5.0.3 on 2025-05-12 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0016_remove_fee_term_remove_fee_year_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'verbose_name': 'FeeStructure', 'verbose_name_plural': 'FeeStructures'},
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.term'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.yearlevel'),
        ),
    ]
