# Generated by Django 5.1.4 on 2025-05-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0017_alter_feestructure_options_alter_feestructure_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='fee_structure',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='fee_type',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='student',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='term',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='year_level',
        ),
        migrations.DeleteModel(
            name='FeeType',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='FeeStructure',
        ),
    ]
