# Generated by Django 5.2.1 on 2025-05-27 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0003_officestaff'),
        ('director', '0019_feetype_feestructure_fee'),
    ]

    operations = [
    ]
