# Generated by Django 5.1.6 on 2025-05-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0004_feetype_feestructure_fee'),
        ('director', '0019_feetype_feestructure_fee'),
    ]

    operations = [
    ]
