# Generated by Django 5.2.1 on 2025-05-27 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0020_merge_0003_officestaff_0019_feetype_feestructure_fee'),
        ('student', '0003_alter_student_enrolment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Late', 'Late')], max_length=10)),
                ('class_period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.classperiod')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'db_table': 'Attendance',
            },
        ),
    ]
