# Generated by Django 5.0.3 on 2025-05-28 08:44

import director.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0021_documenttype_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=director.utils.Document_folder),
        ),
    ]
