# Generated by Django 5.0.3 on 2025-05-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0023_alter_fee_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
