# Generated by Django 5.1.4 on 2025-06-03 19:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0024_alter_fee_razorpay_order_id'),
        ('student', '0003_alter_student_enrolment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='fee_type',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='term',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='year_level',
        ),
        migrations.RemoveField(
            model_name='feetype',
            name='description',
        ),
        migrations.AddField(
            model_name='feetype',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('July', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December'), ('Jan', 'January'), ('Feb', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June')], max_length=20)),
                ('fee_details', models.JSONField(default=dict)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Cheque', 'Cheque')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('receipt_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('signature', models.CharField(max_length=100)),
                ('fee_types', models.ManyToManyField(to='director.feetype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'FeeRecord',
                'verbose_name_plural': 'FeeRecord',
                'db_table': 'FeeRecord',
            },
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='FeeStructure',
        ),
    ]
