# Generated by Django 5.2.1 on 2025-06-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0024_alter_fee_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={},
        ),
        migrations.AddField(
            model_name='address',
            name='block',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='division',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='habitation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='word_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='zone_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='emergency_contact_n0',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='entire_road_distance_from_home_to_school',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='obtain_marks',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='previous_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='total_marks',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='admission_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bankingdetail',
            name='ifsc_code',
            field=models.CharField(max_length=225),
        ),
    ]
