# Generated by Django 5.2.1 on 2025-06-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0021_attendance'),
        ('director', '0024_alter_fee_razorpay_order_id'),
    ]

    operations = [
    ]
