# Generated by Django 5.2.1 on 2025-06-10 20:36

import director.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0025_alter_admission_options_address_block_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=director.utils.Document_folder)),
            ],
            options={
                'db_table': 'File',
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='document_types',
            field=models.ManyToManyField(to='director.documenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='files',
            field=models.ManyToManyField(to='director.file'),
        ),
    ]
