# Generated by Django 5.1.4 on 2025-06-04 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0026_feerecord_amount_paid_feerecord_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerecord',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.term'),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.yearlevel'),
        ),
    ]
