# Generated by Django 5.2.1 on 2025-06-11 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0026_file_remove_document_document_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='files',
        ),
        migrations.AddField(
            model_name='file',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='director.document'),
        ),
    ]
