# Generated by Django 5.1.4 on 2025-06-04 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0027_alter_feerecord_term_alter_feerecord_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerecord',
            name='year_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='director.yearlevel'),
        ),
    ]
