# Generated by Django 5.2.1 on 2025-06-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0027_remove_document_files_file_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='identities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
