# Generated by Django 5.2.1 on 2025-06-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0028_document_identities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='identities',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
