# Generated by Django 5.1.4 on 2025-06-04 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0028_alter_feerecord_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerecord',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='year_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='director.yearlevel'),
            preserve_default=False,
        ),
    ]
