# Generated by Django 5.1.4 on 2025-06-04 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0029_alter_feerecord_late_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feerecord',
            name='year_level',
        ),
    ]
