# Generated by Django 5.1.4 on 2025-06-04 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0030_remove_feerecord_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerecord',
            name='year_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='director.yearlevel'),
            preserve_default=False,
        ),
    ]
