# Generated by Django 5.1.4 on 2025-06-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0031_feerecord_year_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feerecord',
            name='year_level',
        ),
    ]
