# Generated by Django 5.1.4 on 2025-06-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0033_remove_feerecord_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feerecord',
            name='amount_paid',
        ),
    ]
