# Generated by Django 5.1.4 on 2025-06-04 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0034_remove_feerecord_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feerecord',
            name='payment_status',
        ),
    ]
