# Generated by Django 5.1.4 on 2025-06-04 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0035_remove_feerecord_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerecord',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='director.term'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feerecord',
            name='year_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='director.yearlevel'),
            preserve_default=False,
        ),
    ]
