# Generated by Django 5.1.4 on 2025-06-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0036_feerecord_amount_paid_feerecord_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerecord',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=20),
        ),
    ]
