# Generated by Django 5.1.4 on 2025-06-04 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0037_alter_feerecord_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feerecord',
            name='term',
        ),
        migrations.RemoveField(
            model_name='feerecord',
            name='year_level',
        ),
        migrations.AddField(
            model_name='feetype',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='director.term'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearlevel',
            name='fee_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='director.feetype'),
            preserve_default=False,
        ),
    ]
