# Generated by Django 5.1.4 on 2025-06-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0038_remove_feerecord_term_remove_feerecord_year_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerecord',
            name='receipt_number',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
