# Generated by Django 5.1.4 on 2025-06-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0039_alter_feerecord_receipt_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feerecord',
            name='fee_details',
        ),
        migrations.AddField(
            model_name='feerecord',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feerecord',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
