# Generated by Django 5.1.4 on 2025-06-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0040_remove_feerecord_fee_details_feerecord_due_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerecord',
            name='receipt_number',
            field=models.CharField(auto_created=True, blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
