# Generated by Django 5.0.3 on 2025-06-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0041_alter_feerecord_receipt_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearlevel',
            name='fee_type',
        ),
        migrations.AddField(
            model_name='yearlevel',
            name='fee_types',
            field=models.ManyToManyField(related_name='year_levels', to='director.feetype'),
        ),
    ]
