# Generated by Django 5.0.3 on 2025-06-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0042_remove_yearlevel_fee_type_yearlevel_fee_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearlevel',
            options={'verbose_name': 'YearLevel', 'verbose_name_plural': 'YearLevels'},
        ),
    ]
