# Generated by Django 5.0.3 on 2025-06-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0043_alter_yearlevel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearlevel',
            name='fee_types',
        ),
    ]
