# Generated by Django 5.0.3 on 2025-06-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0044_remove_yearlevel_fee_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlevel',
            name='fee_types',
            field=models.ManyToManyField(related_name='year_levels', to='director.feetype'),
        ),
    ]
