# Generated by Django 5.0.3 on 2025-06-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0045_yearlevel_fee_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feetype',
            name='term',
        ),
    ]
