# Generated by Django 5.0.3 on 2025-06-05 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0046_remove_feetype_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='director.term'),
            preserve_default=False,
        ),
    ]
