# Generated by Django 5.0.3 on 2025-06-10 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0047_feetype_term'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feerecord',
            options={'verbose_name': 'Fee Record', 'verbose_name_plural': 'Fee Records'},
        ),
        migrations.AlterModelOptions(
            name='feetype',
            options={'verbose_name': 'Fee Type', 'verbose_name_plural': 'Fee Types'},
        ),
        migrations.AlterModelOptions(
            name='yearlevel',
            options={'verbose_name': 'Year Level', 'verbose_name_plural': 'Year Levels'},
        ),
        migrations.RemoveField(
            model_name='feerecord',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='feerecord',
            name='fee_types',
        ),
        migrations.RemoveField(
            model_name='feetype',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='feetype',
            name='term',
        ),
        migrations.RemoveField(
            model_name='yearlevel',
            name='fee_types',
        ),
        migrations.AlterField(
            model_name='feetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='YearLevelFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.feetype')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.yearlevel')),
            ],
            options={
                'verbose_name': 'Year Level Fee',
                'verbose_name_plural': 'Year Level Fees',
                'db_table': 'YearLevelFee',
            },
        ),
        migrations.AddField(
            model_name='feerecord',
            name='year_level_fees',
            field=models.ManyToManyField(to='director.yearlevelfee'),
        ),
    ]
