# Generated by Django 5.0.3 on 2025-06-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0049_feerecord_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feerecord',
            old_name='razorpay_signature',
            new_name='razorpay_signature_id',
        ),
    ]
