# Generated by Django 5.0.3 on 2025-06-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0050_rename_razorpay_signature_feerecord_razorpay_signature_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerecord',
            name='is_cheque_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='month',
            field=models.CharField(choices=[('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June')], max_length=20),
        ),
    ]
