# Generated by Django 5.1.6 on 2025-06-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_initial'),
        ('director', '0029_alter_document_identities'),
        ('director', '0050_rename_razorpay_signature_feerecord_razorpay_signature_id'),
    ]

    operations = [
    ]
