# Generated by Django 5.1.6 on 2025-05-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_profile',
            field=models.FileField(default=1, upload_to='profile_pics/'),
            preserve_default=False,
        ),
    ]
