# Generated by Django 5.1.6 on 2025-06-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('authentication', '0003_user_user_profile'),
    ]

    operations = [
    ]
