# Generated by Django 5.0.3 on 2024-08-22 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'GuardianType',
                'verbose_name_plural': 'GuardianTypes',
                'db_table': 'GuardianType',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_relation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
                'db_table': 'Guardian',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('enrolment_date', models.DateField()),
                ('classes', models.ManyToManyField(related_name='Student', to='director.classperiod')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.guardian')),
                ('guardian_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.guardiantype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
            ],
            options={
                'verbose_name': 'StudentGuardian',
                'verbose_name_plural': 'StudentGuardians',
                'db_table': 'StudentGuardian',
            },
        ),
        migrations.CreateModel(
            name='StudentYearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.yearlevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.schoolyear')),
            ],
            options={
                'verbose_name': 'StudentYearLevel',
                'verbose_name_plural': 'StudentYearLevels',
                'db_table': 'StudentYearLevel',
            },
        ),
    ]
