# Generated by Django 5.2.1 on 2025-06-18 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'GuardianType',
                'verbose_name_plural': 'GuardianTypes',
                'db_table': 'GuardianType',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=50)),
                ('annual_income', models.IntegerField()),
                ('means_of_livelihood', models.CharField(choices=[('Govt', 'Government'), ('Non-Govt', 'Non-Government')], default='Govt', max_length=10)),
                ('qualification', models.CharField(max_length=300)),
                ('occupation', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=300)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_relation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
                'db_table': 'Guardian',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=250)),
                ('mother_name', models.CharField(max_length=250)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('OBC', 'Other Backward Class'), ('GEN', 'General')], default='GEN', max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('blood_group', models.CharField(max_length=5)),
                ('number_of_siblings', models.IntegerField()),
                ('classes', models.ManyToManyField(related_name='Student', to='director.classperiod')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.guardian')),
                ('guardian_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.guardiantype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
            ],
            options={
                'verbose_name': 'StudentGuardian',
                'verbose_name_plural': 'StudentGuardians',
                'db_table': 'StudentGuardian',
            },
        ),
        migrations.CreateModel(
            name='StudentYearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.yearlevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='director.schoolyear')),
            ],
            options={
                'verbose_name': 'StudentYearLevel',
                'verbose_name_plural': 'StudentYearLevels',
                'db_table': 'StudentYearLevel',
            },
        ),
    ]
