# Generated by Django 5.0.2 on 2024-05-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_guardian_user'),
        ('student', '0002_alter_student_user'),
    ]

    operations = [
    ]
