# Generated by Django 5.1.6 on 2025-04-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
