# Generated by Django 5.0.3 on 2025-06-16 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_enrolment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentyearlevel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_year_levels', to='student.student'),
        ),
    ]
