# Generated by Django 5.2.1 on 2025-06-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_enrolment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolment_date',
        ),
        migrations.AddField(
            model_name='guardian',
            name='annual_income',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardian',
            name='designation',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardian',
            name='means_of_livelihood',
            field=models.CharField(choices=[('Govt', 'Government'), ('Non-Govt', 'Non-Government')], default='Govt', max_length=10),
        ),
        migrations.AddField(
            model_name='guardian',
            name='occupation',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardian',
            name='qualification',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('OBC', 'Other Backward Class'), ('GEN', 'General')], default='GEN', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='height',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='number_of_siblings',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
