# Generated by Django 5.2.1 on 2025-06-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='session_id',
        ),
        migrations.DeleteModel(
            name='AttendanceSession',
        ),
    ]
