# Generated by Django 5.2.1 on 2025-06-11 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_studentattendance_unique_together_and_more'),
        ('director', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='year_level',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='director.yearlevel'),
            preserve_default=False,
        ),
    ]
