# Generated by Django 5.2.1 on 2025-06-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_studentattendance_teacher'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendance',
            old_name='period',
            new_name='session_id',
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('session_id', 'student')},
        ),
    ]
