# Generated by Django 5.1.6 on 2025-06-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('attendance', '0003_rename_period_studentattendance_session_id_and_more'),
    ]

    operations = [
    ]
